### ISSUE TITLE
tk_choose_file 函数的返回值无法访问

### ISSUE THREAD

**Issue by Gravity-of-eath** [zlgopen/awtk#916]
这个GDB的调用栈
#0  __strcpy_avx2 () at ../sysdeps/x86_64/multiarch/strcpy-avx2.S:301
#1  0x00007ffff7baa9a4 in tk_strcpy (dst=0x55555555a040 <file> "", src=0x56bdfe20 <error: Cannot access memory at address 0x56bdfe20>) at src/tkc/utils.c:310
#2  0x0000555555556d25 in on_open_click (ctx=0x555555e987c0, e=0x7fffffffcea0) at src/pages/home_page.c:24
#3  0x00007ffff7b76fbc in emitter_dispatch (emitter=0x555555e08860, e=0x7fffffffcea0) at src/tkc/emitter.c:131
#4  0x00007ffff7a45ecb in widget_dispatch (widget=0x555555e29730, e=0x7fffffffcea0) at src/base/widget.c:1367
#5  0x00007ffff79d1c0b in button_on_event (widget=0x555555e29730, e=0x7fffffffd3a0) at src/widgets/button.c:246
#6  0x00007ffff7a45e68 in widget_dispatch (widget=0x555555e29730, e=0x7fffffffd3a0) at src/base/widget.c:1357
#7  0x00007ffff7a4df13 in widget_on_pointer_up_after_children (widget=0x555555e29730, e=0x7fffffffd3a0) at src/base/widget.c:3240
#8  0x00007ffff7a4e0dd in widget_on_pointer_up_impl (widget=0x555555e29730, e=0x7fffffffd3a0) at src/base/widget.c:3262
#9  0x00007ffff7a4e17b in widget_on_pointer_up (widget=0x555555e29730, e=0x7fffffffd3a0) at src/base/widget.c:3271
#10 0x00007ffff7a4dedd in widget_on_pointer_up_children (widget=0x555555e83020, e=0x7fffffffd3a0) at src/base/widget.c:3231
#11 0x00007ffff7a4e06d in widget_on_pointer_up_impl (widget=0x555555e83020, e=0x7fffffffd3a0) at src/base/widget.c:3253
#12 0x00007ffff7a4e17b in widget_on_pointer_up (widget=0x555555e83020, e=0x7fffffffd3a0) at src/base/widget.c:3271
#13 0x00007ffff7a4dedd in widget_on_pointer_up_children (widget=0x555555e987c0, e=0x7fffffffd3a0) at src/base/widget.c:3231
#14 0x00007ffff7a4e06d in widget_on_pointer_up_impl (widget=0x555555e987c0, e=0x7fffffffd3a0) at src/base/widget.c:3253
#15 0x00007ffff7a4e17b in widget_on_pointer_up (widget=0x555555e987c0, e=0x7fffffffd3a0) at src/base/widget.c:3271
#16 0x00007ffff7a4dedd in widget_on_pointer_up_children (widget=0x55555557e220, e=0x7fffffffd3a0) at src/base/widget.c:3231
--Type <RET> for more, q to quit, c to continue without paging--Quit

**Comment by Gravity-of-eath** [comment]
![企业微信截图_17337266893987](https://github.com/user-attachments/assets/7e1090de-3474-48d5-8c8d-8cdaf46b1a9b)
我编译了你提供的demo但是运行报错，我的虚拟机是Vmware16.2.3里面运行的Ubuntu 20.04.6 LTS

**Comment by Gravity-of-eath** [comment]
我好像发现问题了，我安装了valgrind后你的demo可以跑起来，但是选择文件的页面是awtk本身带的那个，我这边好像走到tk_choose_file_native这个分支了，我这边弹出的页面Ubuntu原生的文件选择
